### ISSUE TITLE
document-benchmark crashed using wiki dataset

### ISSUE THREAD

**Issue by michaelrun** [RediSearch/RediSearchBenchmark#22]
I'm using `Redis 7.2.0 (29622276/0) 64 bit` and RediSearch module `2.8.13`.  download document-benchmark tool: [RediSeachBenchmark](https://github.com/RediSearch/RediSearchBenchmark/releases/download/v0.1.7/document-benchmark-linux-amd64.tar.gz).
here is the steps to reproduce:
1. wget https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/enwiki-abstract/enwiki-latest-abstract.xml
2. ./document-benchmark -hosts "127.0.0.1:6379" -engine redis -file enwiki-latest-abstract.xml -maxdocs 100000
3. ./document-benchmark -hosts "127.0.0.1:6379" -engine redis -benchmark search -file enwiki-latest-abstract.xml
then RediSearchBenchmark crashed during running:
```
2024/07/18 09:00:59 Using a total of 256 concurrent benchmark workers
2024/07/18 09:00:59 Using input file to produce terms for the benchmarks
2024/07/18 09:00:59 Starting full-text queries benchmark
                 Test time                      Command Rate   Client p50 with RTT(ms)            Total Commands
panic: redis: unexpected type=map[interface {}]interface {} for Slice

goroutine 428 [running]:
main.Benchmark.func1()
        /github/workspace/benchmark.go:172 +0x21c
created by main.Benchmark
        /github/workspace/benchmark.go:166 +0x2bb
```

**Comment by fcostaoliveira** [comment]
Hi there @michaelrun, let me check this until end of week. will reproduce and fix and reply back

**Comment by michaelrun** [comment]
Thanks, @fcostaoliveira, any more information needed, please let me know.
